tags:
    fix: &fix_type bugfix
    fixes: *fix_type
    bugfix: *fix_type
    rsctweak: &tweak_type tweak
    tweak: *tweak_type
    tweaks: *tweak_type
    soundadd: soundadd
    sounddel: sounddel
    add: &add_type rscadd
    adds: *add_type
    rscadd: *add_type
    del: &del_type rscdel
    dels: *del_type
    rscdel: *del_type
    imageadd: imageadd
    imagedel: imagedel
    typo: &typo_type spellcheck
    spellcheck: *typo_type
    balance: &balance_type balance
    rebalance: *balance_type
    tgs: tgs
    code_imp: &code_type code_imp
    code: *code_type
    refactor: refactor
    config: config
    admin: admin
    server: server
