name: Test

on: 
  pull_request:
    types: [closed]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: octokit/graphql-action@v2.x
      id: get_latest_release
      with:
        query: |
          query pullrequest {
            repository(name: "beestation-hornet", owner: "crossedfall") {
              pullRequest(number: 3){
                body
                bodyHTML
                bodyText
              }
            }
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - run: "echo 'latest release: ${{ steps.get_latest_release.outputs.data }}'"
