name: Get PR Body
on:
  pull_request:
    types: [closed]

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_latest_release
        with:
          query: |
            query prbody($owner:String!,$repo:String!,$pr:Int!) {
              repository(owner:$owner,name:$repo) {
                pullRequest(number:$pr) {
                  bodyText            
                }
              }
            }
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          pr: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          touch ./test.txt
          printf "%s" "${{ steps.get_latest_release.outputs.data }}" > ./test.txt
          cat ./test.txt
