name: Make changelogs

on:
  push:
    branches: [master]

jobs:
  MakeCL:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 25
      - name: Python setup
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install ruamel.yaml PyGithub
      - name: Make CL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python tools/changelog/generate_cl.py
      - name: Commit
        run: |
          git config --local user.email "56381746+ss13-beebot@users.noreply.github.com"
          git config --local user.name "ss13-beebot"
          git pull origin master
          git add -A html/changelogs/.
          git commit -m " Automatic changelog generation for PR #$PR_NUMBER [ci skip]" -a || true
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
