name: Make changelogs

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  MakeCL:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 25
          token: ${{ secrets.CL_TOKEN }}
      - name: Python setup
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install ruamel.yaml
      - name: Make CL
        env:
          PR_BODY: ${{ toJson(github.event.pull_request.body) }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        run: python tools/changelog/generate_cl.py "$PR_BODY" $PR_NUMBER "$PR_AUTHOR"
      - name: Commit
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          git config --local user.email "56381746+ss13-beebot@users.noreply.github.com"
          git config --local user.name "ss13-beebot"
          git remote set-url origin https://crossedfall:${{ secrets.CL_TOKEN }}@github.com/Crossedfall/BeeStation-Hornet.git
          git pull origin master
          git add -A html/changelogs/.
          git commit -m " Automatic changelog generation for PR #$PR_NUMBER [ci skip]" -a || true
          git push 
