name: CI

on:
  pull_request:
    types: [opened, reopened]

jobs:
  MakeCL:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Python setup
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: The big one
        env:
          PR_BODY: ${{ toJson(github.event.pull_request.body) }}
          PR_NUMBER: github.event.pull_request.number
        run: python tools/changelog/test.py "$GITHUB_CONTEXT" $PR_NUMBER
      - name: Upload CL
        env:
          PR_NUMBER: github.event.pull_request.number
        uses: actions/upload-artifact@v1
        with:
          name: changelog
          path: html/changelogs/AutoChangeLog-pr-$PR_NUMBER.yml

  CompileCL:
    runs-on: ubuntu-latest
    steps:
      - name: Download CL
        uses: actions/download-artifact@v1
        with:
          name: changelog
      - name: "Setup python"
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: "Install deps"
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml
      - name: "Checkout"
        uses: actions/checkout@v1
        with:
          fetch-depth: 25
      - name: "Compile"
        run: |
          python tools/ss13_genchangelog.py html/changelog.html html/changelogs
      - name: Commit
        run: |
          git config --local user.email "56381746+ss13-beebot@users.noreply.github.com"
          git config --local user.name "ss13-beebot"
          git pull origin master
          git commit -m "Automatic changelog compile [ci skip]" -a || true
      - name: "Push"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

